name: 'spotify_trend_dashboard'
version: '1.0.0'
config-version: 2

profile: 'spotify_trend_dashboard'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_trend_dashboard:
    staging:
      +materialized: view
    marts:
      +materialized: table
